// AUTO-GENERATED by scripts/sync-date-registry.mjs — do not edit by hand.
// Add/remove a file in content/dates/ then run `npm run sync:dates`.
import type { DateTree } from './schema';
import d0 from "./dates/ag1-airport.json";
import d1 from "./dates/ag1-corner-cafe.json";
import d2 from "./dates/ag1-grocery-store.json";
import d3 from "./dates/ag1-kitchen.json";
import d4 from "./dates/ag1-office.json";
import d5 from "./dates/celsius-beach-day.json";
import d6 from "./dates/celsius-grocery-store.json";
import d7 from "./dates/celsius-music-festival.json";
import d8 from "./dates/celsius-nightgym.json";
import d9 from "./dates/celsius-rooftop.json";
import d10 from "./dates/eight-sleep-bedroom-night.json";
import d11 from "./dates/eight-sleep-kitchen.json";
import d12 from "./dates/home.json";
import d13 from "./dates/liquid-iv-airport.json";
import d14 from "./dates/liquid-iv-grocery-store.json";
import d15 from "./dates/liquid-iv-kitchen.json";
import d16 from "./dates/liquid-iv-music-festival.json";
import d17 from "./dates/liquid-iv-office.json";
import d18 from "./dates/oura-beach-day.json";
import d19 from "./dates/oura-bedroom-night.json";
import d20 from "./dates/oura-corner-cafe.json";
import d21 from "./dates/oura-nightgym.json";
import d22 from "./dates/oura-office.json";
import d23 from "./dates/red-bull-airport.json";
import d24 from "./dates/red-bull-music-festival.json";
import d25 from "./dates/starbucks-corner-cafe.json";
import d26 from "./dates/whoop-airport.json";
import d27 from "./dates/whoop-bedroom-night.json";
import d28 from "./dates/whoop-corner-cafe.json";
import d29 from "./dates/whoop-nightgym.json";
import d30 from "./dates/whoop-office.json";
import d31 from "./dates/zen-bedroom-night.json";
import d32 from "./dates/zen-office.json";
import d33 from "./dates/zyn-nightgym.json";

// eslint-disable-next-line
// JSON literals widen string unions; runtime shape is guarded in registry.ts
// and semantics by tools/validate-core.mjs.
export const dateFiles = [d0 as unknown as DateTree, d1 as unknown as DateTree, d2 as unknown as DateTree, d3 as unknown as DateTree, d4 as unknown as DateTree, d5 as unknown as DateTree, d6 as unknown as DateTree, d7 as unknown as DateTree, d8 as unknown as DateTree, d9 as unknown as DateTree, d10 as unknown as DateTree, d11 as unknown as DateTree, d12 as unknown as DateTree, d13 as unknown as DateTree, d14 as unknown as DateTree, d15 as unknown as DateTree, d16 as unknown as DateTree, d17 as unknown as DateTree, d18 as unknown as DateTree, d19 as unknown as DateTree, d20 as unknown as DateTree, d21 as unknown as DateTree, d22 as unknown as DateTree, d23 as unknown as DateTree, d24 as unknown as DateTree, d25 as unknown as DateTree, d26 as unknown as DateTree, d27 as unknown as DateTree, d28 as unknown as DateTree, d29 as unknown as DateTree, d30 as unknown as DateTree, d31 as unknown as DateTree, d32 as unknown as DateTree, d33 as unknown as DateTree];
